language: java
jdk: openjdk11
sudo: required
dist: trusty
services:
- docker
script:
- export BUILD_TS=$(date +%Y%m%d-%H%M%S)
- mvn clean verify
- echo "$DOCKER_PASSWORD" | docker login quay.io -u "$DOCKER_USERNAME" --password-stdin
- docker build -t quay.io/woditschka/tfa-web:$BUILD_TS -t quay.io/woditschka/tfa-web:latest .
- docker push quay.io/woditschka/tfa-web:$BUILD_TS
- docker push quay.io/woditschka/tfa-web:latest
env:
  global:
  - secure: J4HMS0duszjpEehHgLg3rpc1MMYUUPm0B83mmvlGiRKxMtTBhRK9YtR/LxOR7Itd85PbmUGOXfhl9fT5dj4o9cMzx+t1YbTohaZ5kHwEALqQnXxLsJVGhFh4omOd+psOTjjDyGLgzKkliDFuK3pQB1n0k4bjLq4a2LU2/hIii9XQ/b+oG4mADJvEs7jAswMDXbMLZ7YgYYfTh0suLFp0RzpTXfa08QI7ACy7AwYC+jkRPNhHqZUEU6aCKUrWI/1M+Bd6JxRIqwiYk1R8IxDbVzb8kmptr4INGgIInshsrH3UG3kcj/Kn/dZUmGJbydStrWrCFTOY02SclqgI7RRAFdBiz0Wu4oJ6F35oktcV9m15gsPyY6yXpYpNa90O3UlzAHvbxhhyKc/InsbTVHZ45ti+LMEliNHl/7j9eddkyd7DEEAD417bAIYQxBZHYUQzuGZMIWDisyFSfvAkqBlXqQt8/Yq81NeE2qtiFKHfohNtYgNXh0kKkbDp7zC/AwhgsvaticWOMmNtW6VDvxthuuNvGNpmydyCseQEl8vmfYpr+hDXWpCQ0R6RJZC7oeeKsooP0k877K1AQvEq1Pj9Jl7VBjepYQUdOxAWDX+Pi5StYvqYd4ctBa4/9WF7gzyh67YHpECV6y/K5EZ+elXbLa1h7tpGZMDTWgDy2hXY92Q=
  - secure: sFh1h8tWlgosiNHeEEVyoyUhU2f5NCFwFn+L2qey+8MO82qxFNY3a36WTj7KvnNFTGWw/PA7iaBg5LQHkoHA71cBdsf238Z1Jg8cvMPfl5AMNOQAqElt2c88K+6EE4LgpQXpvJLCnTC5n0ERZl72imHbPCwVI57KFh4c481lwho2bmOdOFjyjRPGZgdUxrQjte6/+n72iU1zVZVpkx0POtq1tV08sueid/149u+yIsvv+fra/hxqlhMc05GdrFanKk//RWuxn0g2wx/g23t8ib+9isAN5FeoVA3b9qy4CFG7YJf9kZ87tyJ2dLUrC3VcLxjCkO9utlRKorxL3/BEvn9pcMAMUv92EYHSw9frifxptzUt9EpvQUhpdmEaqouYVs9TRQJAFJC0+p0lc5JQi1QMQiMPZYvhsW2oWl6NzTRc6PJIOCMFXITnMGpOWP0UMkkG/XXypreKJKRd5BJCl1PHXVFefSDpxPsbP6v3+3DyUVKlUUo4AZFY6xqP5sjhce5in19oWqdgRc6QUOZvkje/I8yOcV2Pr1ksYEGB/1qADdp4XMEEL0vqXBi86Jx4s2zMxX3DmNszblqpR06QRlEKndYvPQNvW00L0xBNwbKyZF2x4rBoKFPUcLoNXA3S+VPtICCVA/z/wd+nhwNqWvbuRX8L1yEkWbXhvudaCDA=
